services:
  - type: web
    name: dentalreserve
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn dental_now:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    healthCheckPath: /health
    autoDeploy: true